### PR TITLE
Proposal: Ban user instead of restriction

### PR DESCRIPTION
**Pull request by slawiko**
Addressing issue mentioned in https://github.com/umputun/tg-spam/pull/27#issuecomment-1866890846

### CODE REVIEW

**Comment by umputun** [comment]
> But also we could really ban user instead of restricting it (I prepared https://github.com/umputun/tg-spam/pull/39). This way the preserve-unbanned flag will not be needed, although I would keep only_if_banned in unban API call just for improbable situation when bot will mess up some IDs and innocent user is removed from the group. Anyways let's continue discussion in the PR, if you think it is needed

Can you remind me what the end goal? Is it to keep users in the group after the ban? Any particular use case outside of this one? Is this `BanChatMemberConfig` really keep banned users in the group?

My issue with this PR - it changes the fundamentals of the ban mechanics, and I'm not sure if this will work the same or may cause some odd issues. By odd issues, I mean all kinds of unexpected things, like how will it act if one admin tries to ban another, and other edge cases like this.

_Another thing - if this PR is justified and solves a real problem, the change should be very carefully tested with real TG integrations on the real group_

**Comment by slawiko** [comment]
> Is it to keep users in the group after the ban?

Initially yes, that was my intention in https://github.com/umputun/tg-spam/pull/27. But now I realized that it can't be met by design of telegram ban/unban according to what I read in the docs. 

So in fact this PR does not fix any issues (except [obsolete flag elimination](https://github.com/umputun/tg-spam/pull/39/commits/dbfcdbcc863442a1615be78c2202f446c2158e4c), but it is minor) and does not change the end-result. The flow now works fine.

What it does change is the way bot treats user "banned". First of all it makes it logical. I would expect bot to make user banned, and unbanned in case it was false positive, not restricted/unbanned. And secondly (theoretical) it could be that one day telegram API will extend permission restriction object (with message reactions, whatever) and bot will ban insufficiently. Although, I understand the weakness of the second point, first point is already good justification for me to change the code, what about you?

**Comment by umputun** [comment]
Removing all the code about `preserve-unbanned` and `keep` checks is a decent goal. I would suggest making it a separate PR without introducing the changes related to the ban vs. restricted. The rest of the change is something I don't feel safe without extensive testing, so I suggest to isolate it to a separate PR we could play with

**Comment by slawiko** [comment]
Extracted flag removal in separate PR: https://github.com/umputun/tg-spam/pull/42

now this PR contains only ban-related change. I tested it in my test group in telegram - looks fine.

**Comment by slawiko** [comment]
Hey @umputun 
are you waiting for some action from my side? I'm ready to act if needed :)

**Comment by umputun** [comment]
> Hey @umputun are you waiting for some action from my side? I'm ready to act if needed :)

all good, thx

**Pull request merged**
